name: Deploy static content to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v2
        with:
          # Upload the specific HTML file you want to deploy
          name: Proyecto1_Visualizacion_RMarkdown.html
          path: Proyecto1_Visualizacion_RMarkdown.html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
